___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
print(np.__version__)
np.show_config()


1.21.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [8]:
print(np.arange(0, 11))

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [9]:
print(np.full((5,5), 0))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [37]:
z = np.random.randint(0, 100, 20)
print(z)
print(np.nonzero(z))

[92 81 50 44 88 97 61 93 56 90 51 91  5 38 92 41 51 87 16  1]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [38]:
print(f'Среднее значение: {np.mean(z)}')
print(f'Медиана: {np.median(z)}')
print(f'Стандартное отклонение: {np.std(z)}')

Среднее значение: 61.25
Медиана: 58.5
Стандартное отклонение: 30.09298090917548


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [131]:
a = np.random.random((4, 2))
b = np.random.random((2, 2))
m = a @ b
print(m)

[[0.57322589 0.58310329]
 [0.15052856 0.08487018]
 [0.51262618 0.74468086]
 [0.54949865 0.61012113]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [139]:
r = np.reshape(m, (8))
print(r)
print(f'Минимальное значение: {np.min(r)}')
print(f'Максимальное значение: {np.max(r)}')
r[r.argmax()] = 0
r

[0.57322589 0.58310329 0.15052856 0.08487018 0.51262618 0.
 0.54949865 0.61012113]
Минимальное значение: 0.0
Максимальное значение: 0.6101211302168861


array([0.57322589, 0.58310329, 0.15052856, 0.08487018, 0.51262618,
       0.        , 0.54949865, 0.        ])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [141]:
for i in range(len(m[:-1])):
    print(np.correlate(m[0], m[i+1]))

[0.13577495]
[0.2938506]
[0.31498685]


Дано матрицю. Знайти ранг матриці:

In [67]:
a = np.array([[1, 4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [68]:
from numpy import linalg as LA

print(LA.matrix_rank(a))

3


Знайти визначник матриці:

In [85]:
print(round(LA.det(a)))

440


Знайти власні значення та власні вектори матриці: 

In [92]:
b = LA.eig(a)
print(b)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
       -4.56760167-3.20389947j]), array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
        -0.31386258+0.47450898j],
       [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
        -0.07049527-0.4090732j ],
       [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
         0.7099444 -0.j        ]]))


Знайдіть число, що найчастіше зустрічається в масиві:

In [162]:
np.random.seed(10)
a = np.random.randint(0,10,50)
print(a)

print(f'Чаще всего встречается число: {np.bincount(a).argmax()}')

[9 4 0 1 9 0 1 8 9 0 8 6 4 3 0 4 6 8 1 8 4 1 3 6 5 3 9 6 9 1 9 4 2 6 7 8 8
 9 2 0 6 7 8 1 7 1 4 0 8 5]
Чаще всего встречается число: 8


Виведіть лише парні числа, що діляться на 5:

In [167]:
np.random.seed(10)
a = np.random.randint(0,10,50)
print(a)
b = a[a % 2 == 0]
c = b[b % 5 == 0]
print(c)

[4 4 6 8 4 9 2 1 1 6 3 4 5 4 0 2 8 0 7 6 5 8 2 2 0 1 2 3 5 7 8 7 7 6 9 2 0
 4 5 4 6 9 0 4 6 4 9 8 0 7]
[4 4 6 8 4 2 6 4 4 0 2 8 0 6 8 2 2 0 2 8 6 2 0 4 4 6 0 4 6 4 8 0]
[0 0 0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [93]:
a = np.array([[2, 5], [1, -10]])
b = np.array([1, 3])
c = np.linalg.solve(a, b)
print(c)

[ 1.  -0.2]
